### ISSUE TITLE
Package can't run

### ISSUE THREAD

**Issue by lewatt23** [eddywm/simple_slider#3]
Hello thanks for the package am getting the following errors when i install it,
`
../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.4.2/lib/cached_network_image.dart:210:34: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
`

**Comment by w32blaster** [comment]
Hey, I have the same issue :(

**Comment by lewatt23** [comment]
it seems like the package is not more maintained ....
