### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by abhikhedekar4241** [eddywm/simple_slider#4]
Because every version of simple_slider depends on cached_network_image ^0.4.1 and creative depends on cached_network_image 0.7.0, simple_slider is forbidden.
So, because creative depends on simple_slider ^0.0.1, version solving failed.
pub get failed (1; So, because creative depends on simple_slider ^0.0.1, version solving failed.)

**Comment by ilkerx** [comment]
+1 with @abhikhedekar4241

**Comment by abhikhedekar4241** [comment]
I used carousel slider. That's perfect.
